import os
import tempfile
from pathlib import Path
from typing import Optional

import pypandoc
from weasyprint import HTML


def render_pdf_from_html(html: str) -> bytes:
    """HTML -> PDF via WeasyPrint. The template's own <style> block (already
    embedded in the rendered HTML) drives all visual styling — no separate
    CSS is injected here."""

    return HTML(string=html).write_pdf()


def render_docx_from_html(html: str, reference_docx: Optional[Path] = None) -> bytes:
    """HTML -> DOCX via Pandoc.

    Pandoc's HTML reader ignores CSS entirely — it maps structure (headings,
    bold/italic, tables, lists) onto Word *styles*, and takes the look of
    those styles from `reference_docx` (`--reference-doc`). That file is
    therefore the only way to make the DOCX match the PDF's colours and
    fonts; without it Word's plain defaults are used and the output looks
    nothing like the PDF. Reference docs are generated by
    rendering/assets/docx_templates/generate_reference_docs.py and mapped per
    template in rendering/html_templates.py::get_docx_reference_path.
    """

    extra_args: list[str] = []
    if reference_docx is not None and Path(reference_docx).is_file():
        extra_args.append(f"--reference-doc={reference_docx}")

    fd, tmp_path = tempfile.mkstemp(suffix=".docx")
    os.close(fd)
    try:
        pypandoc.convert_text(
            html, "docx", format="html", outputfile=tmp_path, extra_args=extra_args
        )
        with open(tmp_path, "rb") as f:
            return f.read()
    finally:
        os.unlink(tmp_path)
