"""add extracted_markdown

Revision ID: 872db9f9115a
Revises: 
Create Date: 2026-07-19 15:00:19.684239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '872db9f9115a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('knowledge_documents', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('knowledge_documents', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('knowledge_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('knowledge_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('requirement_documents', sa.Column('extracted_markdown', sa.Text(), nullable=True))
    op.add_column('requirement_documents', sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('requirement_documents', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('requirement_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('requirement_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'is_first_login',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_first_login',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('requirement_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('requirement_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('requirement_documents', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('requirement_documents', 'parsed_data')
    op.drop_column('requirement_documents', 'extracted_markdown')
    op.alter_column('knowledge_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('knowledge_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('knowledge_documents', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('knowledge_documents', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
